### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive-transitions-slide#11]
I was going to try to address issue #10, but ```npm install``` has some issues. Using ```npm install --dev``` just installs recursively, infinitely. Running ```npm install``` by itself yields this error:

```
Failed at the ractive-transitions-slide@0.2.1 prepublish script 'npm run build'.
npm ERR! This is most likely a problem with the ractive-transitions-slide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
```
I noticed a lot of the dependencies were deprecated or unsupported, so that might have something to do with it. Seems strange that a simple JS file would have a such a long stack of dependencies, though.

**Comment by Rich-Harris** [comment]
> Using `npm install --dev` just installs recursively, infinitely

lol, never do that! AFAICT it installs every package's dev dependencies until you run out of space on your machine.

Not sure why the build didn't work for you, but try now – I've simplified the build process a bit and released it as 0.3.0. (I know, it's weird having a build process for something so simple. It's more about consistency than anything else, e.g. I don't want to have to think about getting the UMD block right. Also I've been spoilt by Babel and can't live without ES6.)

Can't investigate the other issues you raised right now, but hopefully this helps in the meantime

**Comment by matthew-dean** [comment]
> AFAICT it installs every package's dev dependencies until you run out of space on your machine.

o_O

Okay, then, I'll try again. ^_^

**Comment by matthew-dean** [comment]
Closing since this works for me now anyway.
